#!/usr/bin/env python3
"""Generate a path-independent manifest for the production RIFT build.

Only files that can affect the production analyzer or its public artifact
contract are included.  Baseline implementations are deliberately excluded so
an unrelated M3 edit cannot change the production-core identity.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path


CORE_FILES = (
    "cli/production_entry.cpp",
    "cli/production_main.cpp",
    "cli/production_main.h",
    "scripts/generate_embedded_manifest.py",
)
CORE_TREES = ("core/production", "include/rift/core")
CORE_EXCLUDES = ("core/production/production_smoke.cpp",)
SCHEMA_TREE = "schema"


def selected_files(
    root: Path,
    fixed: tuple[str, ...],
    trees: tuple[str, ...],
    excludes: tuple[str, ...] = (),
) -> list[Path]:
    paths = {root / relative for relative in fixed}
    for relative in trees:
        tree = root / relative
        if not tree.is_dir():
            raise ValueError(f"required production tree is missing: {relative}")
        paths.update(path for path in tree.rglob("*") if path.is_file())
    paths.difference_update(root / relative for relative in excludes)
    missing = sorted(path for path in paths if not path.is_file())
    if missing:
        raise ValueError(
            "required production files are missing: "
            + ", ".join(path.relative_to(root).as_posix() for path in missing)
        )
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def tree_digest(root: Path, paths: list[Path]) -> tuple[str, list[dict[str, str]]]:
    digest = hashlib.sha256()
    records: list[dict[str, str]] = []
    for path in paths:
        relative = path.relative_to(root).as_posix()
        relative_bytes = relative.encode("utf-8")
        payload = path.read_bytes()
        digest.update(len(relative_bytes).to_bytes(8, "big"))
        digest.update(relative_bytes)
        digest.update(len(payload).to_bytes(8, "big"))
        digest.update(payload)
        records.append({"path": relative, "sha256": hashlib.sha256(payload).hexdigest()})
    if not records:
        raise ValueError("an embedded build manifest cannot be empty")
    return digest.hexdigest(), records


def write_if_changed(path: Path, payload: bytes) -> None:
    if path.is_file() and path.read_bytes() == payload:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # CMake should schedule one producer, but the generator is also used by
    # verification tooling.  A unique temporary in the destination directory
    # keeps concurrent identical invocations atomic instead of letting one
    # process rename another process's fixed `.tmp` file.
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=path.name + ".", suffix=".tmp"
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(payload)
            output.flush()
            os.fsync(output.fileno())
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output-header", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    arguments = parser.parse_args()

    root = arguments.source_root.resolve(strict=True)
    core_paths = selected_files(
        root, CORE_FILES, CORE_TREES, CORE_EXCLUDES
    )
    schema_paths = selected_files(root, (), (SCHEMA_TREE,))
    core_sha256, core_records = tree_digest(root, core_paths)
    schema_sha256, schema_records = tree_digest(root, schema_paths)
    manifest = {
        "schema_version": "rift.build-manifest.v1",
        "identity_policy": "relative-path-and-content-v1",
        "production_core_sha256": core_sha256,
        "schema_bundle_sha256": schema_sha256,
        "production_core_files": core_records,
        "schema_files": schema_records,
    }
    encoded_manifest = (
        json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    ).encode("utf-8")
    manifest_sha256 = hashlib.sha256(encoded_manifest).hexdigest()
    header = f"""// Generated by scripts/generate_embedded_manifest.py. Do not edit.
#ifndef RIFT_GENERATED_BUILD_MANIFEST_H
#define RIFT_GENERATED_BUILD_MANIFEST_H

namespace rift::build_manifest {{
inline constexpr char kIdentityPolicy[] = "relative-path-and-content-v1";
inline constexpr char kProductionCoreSha256[] = "{core_sha256}";
inline constexpr char kSchemaBundleSha256[] = "{schema_sha256}";
inline constexpr char kManifestSha256[] = "{manifest_sha256}";
}}  // namespace rift::build_manifest

#endif
""".encode("utf-8")
    write_if_changed(arguments.output_json, encoded_manifest)
    write_if_changed(arguments.output_header, header)
    print(
        "PASS",
        f"core_files={len(core_records)}",
        f"schema_files={len(schema_records)}",
        f"core_sha256={core_sha256}",
        f"schema_sha256={schema_sha256}",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
